# Generated by Django 4.1.7 on 2023-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccounttype",
            name="annual_interest_rate",
        ),
        migrations.RemoveField(
            model_name="bankaccounttype",
            name="interest_calculation_per_year",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="initial_deposit_date",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="interest_start_date",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
