# Generated by Django 4.1.7 on 2023-04-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userbankaccount_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccounttype",
            name="annual_interest_rate",
        ),
        migrations.RemoveField(
            model_name="bankaccounttype",
            name="interest_calculation_per_year",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="interest_start_date",
        ),
    ]
