# Generated by Django 4.1.7 on 2023-04-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_bankaccounttype_annual_interest_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="phone_number",
        ),
    ]
